version: "3.7"
services:
  api:
    container_name: youtube-search-server
    build: "./youtube-search-server"
    restart: always
    volumes:
      - ./youtube-search-server:/home/app
    ports:
      - 3000:3000
    environment:
      SECRET: mysecretkey
      TOKEN_EXP: 3600000
      TOKEN_EXP_REFRESH: 120
      TIMEZONE: America/Sao_Paulo
      GOOGLE_KEY: #GOOGLE_KEY
      MONGO_DB: #MONGO_DB
      MONGO_HOST: #MONGO_HOST
      MONGO_PORT: #MONGO_PORT
      MONGO_USER: #MONGO_USER
      MONGO_PWD: #MONGO_PWD