version: "3.7"
services:
  api:
    container_name: yss-container
    build: "./youtube-search-server"
    restart: always
    ports:
      - 3000:3000
    environment:
      SECRET: mysecretkey
      TOKEN_EXP: 3600000
      TOKEN_EXP_REFRESH: 120
      TIMEZONE: America/Sao_Paulo
      GOOGLE_KEY: AIzaSyCkZAIsmNZ5cV9Em_npEssep_o10Pl2Z9M
      MONGO_USER: mongoDbUser
      MONGO_PWD: nov@senh@m0ng0
      MONGO_HOST: cluster0-ycvck.gcp.mongodb.net
      MONGO_DB: youtube
      MONGO_PROTOCOL: mongodb+srv
  client:
    container_name: ysc-container
    build: "./youtube-search-client"
    ports:
      - 8080:80