version: "3.7"
services:
  api:
    container_name: youtube-search-server
    build: "./youtube-search-server"
    restart: always
    volumes:
      - ./youtube-search-server:/home/app
    ports:
      - 3000:3000
    environment:
      SECRET: mysecretkey
      TOKEN_EXP: 3600000
      TOKEN_EXP_REFRESH: 120
      TIMEZONE: America/Sao_Paulo
      GOOGLE_KEY: #GOOGLE_KEY
      MONGO_URL: #MONGO_URL
  client:
    container_name: youtube-search-client
    build: "./youtube-search-client"
    volumes:
      - ./youtube-search-client:/home/app
    ports:
      - 8080:80